from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_required_public_files_exist() -> None:
    required = [
        ROOT / "README.md",
        ROOT / "LICENSE",
        ROOT / "SECURITY.md",
        ROOT / "docs" / "ARCHITECTURE.md",
        ROOT / "docs" / "RUNTIME_SETUP.md",
        ROOT / "docs" / "VALIDATION.md",
        ROOT / "docs" / "DESIGN_DECISIONS.md",
        ROOT / "docs" / "FAILURE_MODES.md",
        ROOT / "examples" / "audit_pack_sample.json",
        ROOT / "scripts" / "doctor.py",
        ROOT / ".github" / "workflows" / "sanity.yml",
    ]
    for path in required:
        assert path.exists(), f"missing: {path}"


def test_bounded_reference_source_set_present() -> None:
    raw = ROOT / "data" / "raw"
    expected = {
        "eu_ai_act_timeline_implementation.pdf",
        "nist_ai_600-1_genai_profile.pdf",
        "nist_ir_8596_cyber_ai_profile_iprd.pdf",
        "owasp_top10_llm_apps_v2025.pdf",
    }
    present = {p.name for p in raw.glob("*.pdf")}
    assert expected.issubset(present)


def test_readme_exposes_low_friction_paths() -> None:
    txt = (ROOT / "README.md").read_text(encoding="utf-8")
    for marker in ["make smoke", "make doctor", "make index", "make app", "data/raw/"]:
        assert marker in txt


def test_public_docs_avoid_unwanted_markers() -> None:
    haystack = []
    for path in [ROOT / "README.md", *sorted((ROOT / "docs").glob("*.md"))]:
        haystack.append(path.read_text(encoding="utf-8").lower())
    text = "\n".join(haystack)

    banned = [
        "this project is designed to demonstrate",
        "portfolio",
        "personal work",
        "demo repo",
        "codex",
        "chatgpt",
        "generated by code",
    ]
    for marker in banned:
        assert marker not in text, marker
